research_task:
  description: >
    Conduct an in-depth financial research about {company}
    Include analysis of financial statements, market trends, competitors, risks, and opportunities.
    Focus on uncovering the most relevant and recent information that impacts {company}'s financial position.
  expected_output: >
    A list with 10 bullet points highlighting the most relevant financial insights, 
    trends, risks, and opportunities for {company}.
  agent: researcher

analysis_task:
  description: >
    Take the research insights and expand each point into a full, structured report section.
    The report should cover financial performance, market position, risks, and opportunities,
    with clear explanations and actionable conclusions for stakeholders.
  expected_output: >
    A comprehensive financial research report with well-structured sections, 
    written in markdown (without '```'), covering each of the main insights 
    in detail with supporting context and analysis.
  agent: analyst
  context:
    - research_task   # 👈 note the dash, makes it a list
  output_file: output/report.md
