coding_task:
  description: >
    Write Python code to accomplish the goal: {assignment}.
  expected_output: >
    A text file containing the Python code along with its execution output.
  agent: coder
  output_file: output/code.txt

